name: Node.js Lint Workflow

on: 
    pull_request:
        branches: develop

jobs: 
    lint:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Navigate to stocks directory
              run: cd tpg

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                    node-version: '18'
                  
            - name: Install dependencies
              run: cd tpg && yarn install

            - name: Lint with yarn
              run: cd tpg && yarn lint